server:
  port: 8888
spring:
  application:
    name: guohe
  jpa:
      hibernate:
        ddl-auto: update
      database: mysql
      show-sql: true
      generate-ddl: true
  http:
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb
  profiles:
    active: dev
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/guohe3/just/mapper/**.xml
  type-aliases-package: classpath:com.guohe3.just.DO


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



logging:
  level:
    test.springboot.user.mapper: debug