server:
  port: 8888
spring:
  application:
    name: learn
  jpa:
      hibernate:
        ddl-auto: update
      database: mysql
      show-sql: true
      generate-ddl: true
  http:
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb
  profiles:
    active: dev
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:test/springboot/**/**.xml
  type-aliases-package: classpath:test.springboot.**.entity


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#swagger
swagger:
  title: 测试接口文档
  contact:
    name: Ethanp
    url: https://github.com/StarPxc
  base-package: com.pxc
  base-path: /**
  version: 1.0.RELEASE
  description: 测试接口文档
  exclude-path: /error, /ops/**